### ISSUE TITLE
Error on uploading image file

### ISSUE THREAD

**Issue by glen** [snehaq/MailSenderApplication#10]
On trying to upload an image file (zip file) getting an error.
<img width="729" alt="path_when_uploading_file" src="https://cloud.githubusercontent.com/assets/32449/22052784/56887b18-dd72-11e6-8d54-48dcbc4991ea.png">

**Comment by snehaq** [comment]
we have added the changes.Now only correct file extensions will be uploaded.

**Comment by glen** [comment]
Fixed now.
