### ISSUE TITLE
Non authenticated access

### ISSUE THREAD

**Issue by glen** [snehaq/MailSenderApplication#4]
Steps to reproduce

1. Login to application.
2. Copy the url of the application.
3. Logout of the application.
4. Paste the copied url in the address bar of the browser and visit the url.
5. User has access to the page without any authentication challenge.

**Comment by snehaq** [comment]
issue fix will take 3.5 hours to 4 hrs for invalidating the session and prompting log in

**Comment by snehaq** [comment]
issue resolved.please check the same.

**Comment by glen** [comment]
Non authenticated user can still modify the templates.

**Comment by hussain33** [comment]
issue handled for session handling and  authentication and code commited
