### ISSUE TITLE
No validation when setting new templates

### ISSUE THREAD

**Issue by glen** [snehaq/MailSenderApplication#5]
1. Make a request to update/modify the set templates.
2. Deliberately enter incorrect template names - example 'hello_world'
3. Make a request and it is saved in the MailSendingApplication.properties file.
<img width="1157" alt="non validated and authenticated update" src="https://cloud.githubusercontent.com/assets/32449/21973681/66502752-dbe8-11e6-942f-1e80908cc43d.png">

**Comment by snehaq** [comment]
![request](https://cloud.githubusercontent.com/assets/18733737/21978729/da7271e4-dc01-11e6-894a-3fa072b8d7e5.jpg)
![discarding](https://cloud.githubusercontent.com/assets/18733737/21978730/da725cd6-dc01-11e6-8777-8b051314fc86.jpg)

Incorrect template name issue fixed.

**Comment by glen** [comment]
Validation now working, though response is "success" - giving the wrong depiction of the result of the POST request
