### ISSUE TITLE
Incorrect message when setting in valid template

### ISSUE THREAD

**Issue by glen** [snehaq/MailSenderApplication#6]
<img width="1422" alt="success message on invalid template" src="https://cloud.githubusercontent.com/assets/32449/21981484/a8b6d792-dc0d-11e6-96ca-bd7f39bf7d6e.png">
On making a request to set the template - even if the template name is invalid - response is still 'success' - this gives an incorrect impression to the user.

**Comment by hussain33** [comment]
issue resolved please check for appropriate message when template selected
